---

- repo: andrewstuart/vim-kubernetes
- repo: chriskempson/base16-vim
- repo: ctrlpvim/ctrlp.vim
  #- repo: edkolev/tmuxline.vim
- repo: patstockwell/vim-monokai-tasty
- repo: ryanoasis/vim-devicons
- repo: wsdjeg/dein-ui.vim

- repo: fatih/vim-go
  on_ft: go
  hook_add: |-
    let g:go_fmt_fail_silently = 1
    let g:syntastic_go_checkers = ['golint']
    let g:go_highlight_structs = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_function_parameters = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_generate_tags = 1
    let g:go_highlight_format_strings = 1
    let g:go_highlight_variable_declarations = 1
    let g:go_highlight_variable_assignments = 1
    let g:go_auto_type_info = 1
    let g:go_fmt_autosave = 1
    let g:go_mod_fmt_autosave = 1
    let g:go_gopls_enabled = 1

    let g:go_def_mapping_enabled = 0
    let g:go_def_mode='gopls'
    let g:go_info_mode='gopls'

- repo: jparise/vim-graphql
  on_ft: graphql

- repo: vim-airline/vim-airline
  hook_add: |-
    let g:airline_powerline_fonts = 1
    let g:airline_theme='monokai_tasty'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

- repo: vim-airline/vim-airline-themes
