---

- {repo: aliou/bats.vim}

- {repo: chriskempson/base16-vim}

- repo: crusoexia/vim-javascript-lib
  on_ft: ['javascript', 'jsx', 'javascript.jsx']

- {repo: crusoexia/vim-monokai}
- {repo: ctrlpvim/ctrlp.vim}
- {repo: mox-mox/vim-localsearch}
- {repo: ryanoasis/vim-devicons}
- {repo: DanManN/vim-razer}

- {repo: jparise/vim-graphql, on_ft: graphql}

- {repo: Glench/Vim-Jinja2-Syntax, on_ft: sls}
- {repo: saltstack/salt-vim, on_ft: sls}

- {repo: hashivim/vim-terraform, on_ft: terraform}
- {repo: juliosueiras/vim-terraform-completion, on_ft: terraform}

- repo: mhartington/nvim-typescript
  on_ft: typescript
  build: ./install.sh

- repo: vim-airline/vim-airline
  hook_add: |
    let g:airline_powerline_fonts = 1

    let g:airline#extensions#coc#enabled = 1
    let g:airline#extensions#neomake#enabled = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

    let g:airline_theme = 'base16_monokai'

- {repo: vim-airline/vim-airline-themes}

- {repo: wsdjeg/dein-ui.vim}

- {repo: Xuyuanp/nerdtree-git-plugin}
